### ISSUE TITLE
Some links lead to permission denied

### ISSUE THREAD

**Issue by smoh** [marimo-team/spotlights#8]
The "open in marimo" links for anywidget and xDSL in README lead to notebooks not open to public.

(I was able to check them out from the spotlight page anyway but thought you might want to fix them.)

![image](https://github.com/user-attachments/assets/5c7256f6-37a8-4d0b-abbd-ab778cb6f81a)

**Comment by mscolnick** [comment]
Thanks for pointing this out - looks like they were dead links (by default show permission denied)

Fixed in from https://github.com/marimo-team/spotlights/commit/8c5667422594712d609a228f1604a2437e48d437, https://github.com/marimo-team/spotlights/commit/b4d691af69bea5eca7f5281bbc8596cee79e7115

**Comment by mscolnick** [comment]
cc @Haleshot, if you don't mind checking my work, I made these changes directly on `main`

**Comment by Haleshot** [comment]
> cc @Haleshot, if you don't mind checking my work, I made these changes directly on `main`

Thanks a lot for fixing the dead hyperlinks; most of them are from the time I had setup a temporary workspace collection before migrating to @ spotlights. Will see if there are any such possible issues in the repo and fix them in upcoming repos.

@smoh Thanks for pointing it out.
